name: GitHub Actions Demo #workflow name
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
       - name: Hello World
         run: echo "Hello World Job"

       - name: Code Checkout
         uses: actions/checkout@v4

       - name: List the files
         run: ls -lrt

       - name: View the todolist file
         run: cat todolist.md
